### ISSUE TITLE
/main.go:153:49: inst.Def undefined (type ir.Instruction has no field or method Def)

### ISSUE THREAD

**Issue by xyproto** [andybalholm/leaven#1]
Hi,

leaven looks like an interesting project!

I'm trying to compile it, for the first time, but I get these errors:

    ./main.go:153:49: inst.Def undefined (type ir.Instruction has no field or method Def)
    ./main.go:258:27: undefined: ir.BasicBlock

I'm using Go 1.12.1 on 64-bit Arch Linux.

Best regards,
Alexander F. Rødseth

**Comment by mewmew** [comment]
Hi,

I also consider Leaven to be a very interesting project! @pwaller mentioned it to me the other day, so I still have to take a deep dive into the source code.

As one of the authors of [llir/llvm](https://github.com/llir/llvm), this issue likely stems from using an older definition of the [ir.Instruction](https://godoc.org/github.com/llir/llvm/ir#Instruction) interface. Previously, it had a `Def() string` method, which has been renamed (as part of https://github.com/llir/llvm/issues/45) to `LLString() string`.

Similarly, `ir.BasicBlock` has been renamed to [ir.Block](https://godoc.org/github.com/llir/llvm/ir#Block) (as part of https://github.com/llir/llvm/issues/44).

Cheers,
Robin

**Comment by andybalholm** [comment]
Probably leaven should have a go.mod file, to pin it to the version of the library that works.

Andy
