### ISSUE TITLE
Error translating "%66 = fadd double %41, 0.5": unsupported instruction type: *ir.InstFAdd

### ISSUE THREAD

**Issue by xyproto** [andybalholm/leaven#3]
I tried converting [this C source file](https://github.com/xyproto/wallutils/blob/0f5663d308246b3d227fd772c10812e7e6192a7c/xinfo.h) (renamed to `xinfo.c`, and without `#pragma once` at the top).

These are the commands I ran:

    clang -S -emit-llvm -Os xinfo.c
    leaven xinfo.ll

This is the error I got:

    2019/03/27 11:02:38 Error translating "%66 = fadd double %41, 0.5": unsupported instruction type: *ir.InstFAdd

And here is some version information:

    clang version 7.0.1 (tags/RELEASE_701/final)
    go version go1.12.1 linux/amd64

`leaven --version` returns no version number, but it's the latest commit from master.

**Comment by andybalholm** [comment]
There are a lot of unsupported instructions. Pull requests are welcome.

**Comment by xyproto** [comment]
The README does not mention this, so I thought all instructions were supported.

**Comment by andybalholm** [comment]
Sorry about that. I explained that when I first mentioned leaven on golang-nuts, but I forgot to mention it in the README.

**Comment by xyproto** [comment]
It's still a cool project, though. :)
